const types = {
    CATEGORIES_LOAD: "CATEGORIES_LOAD",
    CATEGORIES_LOAD_SUCCESS: "CATEGORIES_LOAD_SUCCESS",
    CATEGORIES_LOAD_FAIL: "CATEGORIES_LOAD_FAIL",
    JOKE_LOAD: "JOKE_LOAD",
    JOKE_LOAD_SUCCESS: "JOKE_LOAD_SUCCESS",
    JOKE_LOAD_FAIL: "JOKE_LOAD_FAIL"
}

export default types;