const types = {
    CATEGORIES_LOAD: "CATEGORIES_LOAD",
    CATEGORIES_LOAD_SUCCESS: "CATEGORIES_LOAD_SUCCESS",
    CATEGORIES_LOAD_FAIL: "CATEGORIES_LOAD_FAIL",
    JOKE_LOAD: "JOKE_LOAD",
    JOKE_LOAD_SUCCESS: "JOKE_LOAD_SUCCESS",
    JOKE_LOAD_FAIL: "JOKE_LOAD_FAIL",
    JOKE_RESET: "JOKE_RESET"
}

export default types;